name: desafio_marvel
description: Flutter Sr challenge by Marvel.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter_localizations:
    sdk: flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.1.1
  flutter_modular: ^5.0.3
  flutter_bloc: ^8.1.2
  shimmer: ^2.0.0
  cached_network_image: ^3.2.3
  unicons: ^2.1.1

dev_dependencies:
  mocktail: ^0.3.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/mu_logo.png